name: Geração de Code Churn

on:
  workflow_dispatch:  # Executar manualmente
  schedule:
    - cron: '0 3 * * 1'  # Toda segunda-feira às 3h UTC

jobs:
  generate-churn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar script de churn
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          OWNER: Tech-Tweakers
          REPO: polaris-python-api
        run: python services/code-churn/main.py

      - name: Commitar resultados
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add static/data/repos/code_churn_*.json
          git commit -m "📊 Atualiza análise de code churn"
          git push
