name: Build Docusaurus to Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout o código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instala dependências
        run: npm ci

      - name: Gera o build
        run: npm run build

      - name: Commit e push do build
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add build
          git commit -m "ci: build Docusaurus para GitHub Pages" || echo "Nada para commitar"
          git push origin main
