name: "[GEN] - Páginas de Métricas (MDX)"

on:
  workflow_dispatch:
    inputs:
        repo:
          description: 'Repositório inserido no portal'
          required: true
          default: 'polaris-python-api'
jobs:
  gerar-paginas:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do repositório
        uses: actions/checkout@v3

      - name: 🧱 Rodar script de geração
        run: |
            export REPOS=${{ github.event.inputs.repo }}
            services/generate-mdx/mdx-gen.sh
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git pull origin main --rebase || echo "⚠️ Pull falhou, seguindo mesmo assim"
            git add docs/
            git commit -m "📊 Cria nova página de métricas" || echo "⚠️ Nenhuma alteração para commitar"
            git push || echo "⚠️ Nenhuma alteração para push"

      - name: ✅ Finalizado
        run: echo "Tudo pronto, comadre!"
