name: "[GEN] - Paginas de Metricas (MDX)"

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repositorio inserido no portal'
        required: true
        default: 'polaris-python-api'

jobs:
  gerar-paginas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Rodar script de geracao
        run: |
          export REPOS=${{ github.event.inputs.repo }}
          chmod +x services/generate-mdx/mdx-gen.sh
          services/generate-mdx/mdx-gen.sh

      - name: Commitar paginas
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "Cria paginas de metricas para ${{ github.event.inputs.repo }}" || echo "Nada novo"
          git push || echo "Nada para push"
